packages:
- .

extra-deps:
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 7deaac6cef43d6247e0a1ab26e982b7ed20a9a44
  subdirs:
    - .
    - liquid-base
    - liquid-bytestring
    - liquid-containers
    - liquid-ghc-prim
    - liquid-prelude
    - liquid-vector
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: e20f1128295b21a87dc2b344b0ba76bbf37441f1

resolver: lts-18.27
nix:
  packages: [cacert, git, hostname, z3]
